### ISSUE TITLE
如何设置默认访问的文件名？

### ISSUE THREAD

**Issue by coolFangjun** [fish-li/ClownFish.HttpServer#1]
大佬请教下：
例如设置为：ip:port/index.html  index.html 的默认页在哪儿可以设置？

**Comment by coolFangjun** [comment]
private void SetUrlVars()
        {
            _rawUrl = _request.RawUrl;
            int p = _rawUrl.IndexOf('?');
            if( p < 0 ) { // 没有查询字符串参数
                _queryString = new NameValueCollection();
                _path = System.Web.HttpUtility.UrlDecode(_rawUrl);
                _query = string.Empty;
            }
            else {
                _path = _rawUrl.Substring(0, p);
                _path = System.Web.HttpUtility.UrlDecode(_path);

                if( p == _rawUrl.Length - 1 ) {   // 问号是最后个字符，没有意义，忽略
                    _query = string.Empty;
                    _queryString = new NameValueCollection();
                }
                else {
                    _query = _rawUrl.Substring(p + 1);
                    _queryString = System.Web.HttpUtility.ParseQueryString(_query);      // 固定按UTF-8来解析
                }
            }
        }

没有判断  _rawUrl =="/"的情况，也就是用户采用 http://192.168.0.2:80  这样子进行访问的时候需要设置一个默认的值 建议改成   _rawUrl = _rawUrl.Length == 1 ? _rawUrl + "index.html" : _rawUrl;

**Comment by fish-li** [comment]
你参考下这个
https://github.com/fish-li/ClownFish.HttpServer/blob/master/src/ClownFish.StaticFileServer.WinApp/ServerOption.config#L20
