### ISSUE TITLE
如何支持mp4等文件？

### ISSUE THREAD

**Issue by coolFangjun** [fish-li/ClownFish.HttpServer#2]
大佬，我添加了mp4的mine以后，GET http://192.168.1.10/temp/video01.mp4 net::ERR_CONTENT_DECODING_FAILED 是否不支持视频播放哇？

**Comment by fish-li** [comment]
是不是文件太大了？你调试一下吧。
静态文件理论上都是可以的。

**Comment by coolFangjun** [comment]
试过咯，文件才几十M，不行哟

**Comment by coolFangjun** [comment]
找到问题咯，您的代码默认开起了的gzip
